const CONFIG = {
  SPREADSHEET_ID: "16BUOfP2vA6gJ3WKCtbXpa_xo_3b4cuHr50QLtBl2ne4",
  TEMPLATE_DOC_ID: "1Gn6nD8MbKkYvk2FMWhvuewO31huD0G1ffFpC2Q9USKs",
  PARENT_FOLDER_ID: "1-lqiztyGH5uSQz9FbyvIK9NBv8_fkozP",
  SHEET_NAME: "Sheet1",
  RECAPTCHA_SECRET: "",
  RECAPTCHA_MIN_SCORE: 0.5,
  REQUIRE_RECAPTCHA: false,
  FECHA_FIRMA: "15 de septiembre de 2026",
};
